// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $eac_entLookup_middleware from "./routes/eac/[entLookup]/_middleware.ts";
import * as $eac_entLookup_azure_cloudLookup_resGroupLookup_resLookups_data_lake_fileSystem_index from "./routes/eac/[entLookup]/azure/[cloudLookup]/[resGroupLookup]/[resLookups]/data-lake/[fileSystem]/index.ts";
import * as $eac_entLookup_azure_cloudLookup_resGroupLookup_resLookups_explorer_db_index from "./routes/eac/[entLookup]/azure/[cloudLookup]/[resGroupLookup]/[resLookups]/explorer/[db]/index.ts";
import * as $eac_entLookup_azure_cloudLookup_api_versions_index from "./routes/eac/[entLookup]/azure/[cloudLookup]/api-versions/index.ts";
import * as $eac_entLookup_azure_cloudLookup_auth_token_index from "./routes/eac/[entLookup]/azure/[cloudLookup]/auth-token/index.ts";
import * as $eac_entLookup_azure_cloudLookup_locations_index from "./routes/eac/[entLookup]/azure/[cloudLookup]/locations/index.ts";
import * as $eac_entLookup_azure_cloudLookup_providers_index from "./routes/eac/[entLookup]/azure/[cloudLookup]/providers/index.ts";
import * as $eac_entLookup_connections_index from "./routes/eac/[entLookup]/connections/index.ts";
import * as $eac_entLookup_index from "./routes/eac/[entLookup]/index.ts";
import * as $eac_entLookup_status_commitId_index from "./routes/eac/[entLookup]/status/[commitId]/index.ts";
import * as $eac_entLookup_status_current from "./routes/eac/[entLookup]/status/current.ts";
import * as $eac_entLookup_status_index from "./routes/eac/[entLookup]/status/index.ts";
import * as $eac_entLookup_users from "./routes/eac/[entLookup]/users.ts";
import * as $eac_middleware from "./routes/eac/_middleware.ts";
import * as $eac_handlers_clouds_check from "./routes/eac/handlers/clouds/check.ts";
import * as $eac_handlers_clouds_connections from "./routes/eac/handlers/clouds/connections.ts";
import * as $eac_handlers_clouds_index from "./routes/eac/handlers/clouds/index.ts";
import * as $eac_handlers_devops_actions_check from "./routes/eac/handlers/devops-actions/check.ts";
import * as $eac_handlers_devops_actions_connections from "./routes/eac/handlers/devops-actions/connections.ts";
import * as $eac_handlers_devops_actions_helpers from "./routes/eac/handlers/devops-actions/helpers.ts";
import * as $eac_handlers_devops_actions_index from "./routes/eac/handlers/devops-actions/index.ts";
import * as $eac_handlers_github_apps_check from "./routes/eac/handlers/github-apps/check.ts";
import * as $eac_handlers_github_apps_connections from "./routes/eac/handlers/github-apps/connections.ts";
import * as $eac_handlers_github_apps_helpers from "./routes/eac/handlers/github-apps/helpers.ts";
import * as $eac_handlers_github_apps_index from "./routes/eac/handlers/github-apps/index.ts";
import * as $eac_handlers_iot_check from "./routes/eac/handlers/iot/check.ts";
import * as $eac_handlers_iot_connections from "./routes/eac/handlers/iot/connections.ts";
import * as $eac_handlers_iot_handler from "./routes/eac/handlers/iot/handler.ts";
import * as $eac_handlers_iot_index from "./routes/eac/handlers/iot/index.ts";
import * as $eac_handlers_secrets_check from "./routes/eac/handlers/secrets/check.ts";
import * as $eac_handlers_secrets_connections from "./routes/eac/handlers/secrets/connections.ts";
import * as $eac_handlers_secrets_helpers from "./routes/eac/handlers/secrets/helpers.ts";
import * as $eac_handlers_secrets_index from "./routes/eac/handlers/secrets/index.ts";
import * as $eac_handlers_source_connections_check from "./routes/eac/handlers/source-connections/check.ts";
import * as $eac_handlers_source_connections_connections from "./routes/eac/handlers/source-connections/connections.ts";
import * as $eac_handlers_source_connections_helpers from "./routes/eac/handlers/source-connections/helpers.ts";
import * as $eac_handlers_source_connections_index from "./routes/eac/handlers/source-connections/index.ts";
import * as $eac_handlers_sources_check from "./routes/eac/handlers/sources/check.ts";
import * as $eac_handlers_sources_connections from "./routes/eac/handlers/sources/connections.ts";
import * as $eac_handlers_sources_index from "./routes/eac/handlers/sources/index.ts";
import * as $eac_index from "./routes/eac/index.ts";
import * as $eac_jwt from "./routes/eac/jwt.ts";
import * as $eac_list from "./routes/eac/list.ts";
import * as $github_webhooks from "./routes/github/webhooks.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/eac/[entLookup]/_middleware.ts": $eac_entLookup_middleware,
    "./routes/eac/[entLookup]/azure/[cloudLookup]/[resGroupLookup]/[resLookups]/data-lake/[fileSystem]/index.ts":
      $eac_entLookup_azure_cloudLookup_resGroupLookup_resLookups_data_lake_fileSystem_index,
    "./routes/eac/[entLookup]/azure/[cloudLookup]/[resGroupLookup]/[resLookups]/explorer/[db]/index.ts":
      $eac_entLookup_azure_cloudLookup_resGroupLookup_resLookups_explorer_db_index,
    "./routes/eac/[entLookup]/azure/[cloudLookup]/api-versions/index.ts":
      $eac_entLookup_azure_cloudLookup_api_versions_index,
    "./routes/eac/[entLookup]/azure/[cloudLookup]/auth-token/index.ts":
      $eac_entLookup_azure_cloudLookup_auth_token_index,
    "./routes/eac/[entLookup]/azure/[cloudLookup]/locations/index.ts":
      $eac_entLookup_azure_cloudLookup_locations_index,
    "./routes/eac/[entLookup]/azure/[cloudLookup]/providers/index.ts":
      $eac_entLookup_azure_cloudLookup_providers_index,
    "./routes/eac/[entLookup]/connections/index.ts":
      $eac_entLookup_connections_index,
    "./routes/eac/[entLookup]/index.ts": $eac_entLookup_index,
    "./routes/eac/[entLookup]/status/[commitId]/index.ts":
      $eac_entLookup_status_commitId_index,
    "./routes/eac/[entLookup]/status/current.ts": $eac_entLookup_status_current,
    "./routes/eac/[entLookup]/status/index.ts": $eac_entLookup_status_index,
    "./routes/eac/[entLookup]/users.ts": $eac_entLookup_users,
    "./routes/eac/_middleware.ts": $eac_middleware,
    "./routes/eac/handlers/clouds/check.ts": $eac_handlers_clouds_check,
    "./routes/eac/handlers/clouds/connections.ts":
      $eac_handlers_clouds_connections,
    "./routes/eac/handlers/clouds/index.ts": $eac_handlers_clouds_index,
    "./routes/eac/handlers/devops-actions/check.ts":
      $eac_handlers_devops_actions_check,
    "./routes/eac/handlers/devops-actions/connections.ts":
      $eac_handlers_devops_actions_connections,
    "./routes/eac/handlers/devops-actions/helpers.ts":
      $eac_handlers_devops_actions_helpers,
    "./routes/eac/handlers/devops-actions/index.ts":
      $eac_handlers_devops_actions_index,
    "./routes/eac/handlers/github-apps/check.ts":
      $eac_handlers_github_apps_check,
    "./routes/eac/handlers/github-apps/connections.ts":
      $eac_handlers_github_apps_connections,
    "./routes/eac/handlers/github-apps/helpers.ts":
      $eac_handlers_github_apps_helpers,
    "./routes/eac/handlers/github-apps/index.ts":
      $eac_handlers_github_apps_index,
    "./routes/eac/handlers/iot/check.ts": $eac_handlers_iot_check,
    "./routes/eac/handlers/iot/connections.ts": $eac_handlers_iot_connections,
    "./routes/eac/handlers/iot/handler.ts": $eac_handlers_iot_handler,
    "./routes/eac/handlers/iot/index.ts": $eac_handlers_iot_index,
    "./routes/eac/handlers/secrets/check.ts": $eac_handlers_secrets_check,
    "./routes/eac/handlers/secrets/connections.ts":
      $eac_handlers_secrets_connections,
    "./routes/eac/handlers/secrets/helpers.ts": $eac_handlers_secrets_helpers,
    "./routes/eac/handlers/secrets/index.ts": $eac_handlers_secrets_index,
    "./routes/eac/handlers/source-connections/check.ts":
      $eac_handlers_source_connections_check,
    "./routes/eac/handlers/source-connections/connections.ts":
      $eac_handlers_source_connections_connections,
    "./routes/eac/handlers/source-connections/helpers.ts":
      $eac_handlers_source_connections_helpers,
    "./routes/eac/handlers/source-connections/index.ts":
      $eac_handlers_source_connections_index,
    "./routes/eac/handlers/sources/check.ts": $eac_handlers_sources_check,
    "./routes/eac/handlers/sources/connections.ts":
      $eac_handlers_sources_connections,
    "./routes/eac/handlers/sources/index.ts": $eac_handlers_sources_index,
    "./routes/eac/index.ts": $eac_index,
    "./routes/eac/jwt.ts": $eac_jwt,
    "./routes/eac/list.ts": $eac_list,
    "./routes/github/webhooks.ts": $github_webhooks,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
